# Generated by Django 5.2.8 on 2026-03-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_assetcategory_shiftdefinition_assetassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='India', max_length=120)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('preferred_role', models.CharField(blank=True, max_length=160)),
                ('current_company', models.CharField(blank=True, max_length=160)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='application_source',
            field=models.CharField(blank=True, default='internal', max_length=80),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='current_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='preferred_contact_channel',
            field=models.CharField(blank=True, default='email', max_length=40),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='stage_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=120),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='experience_max_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='experience_min_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=190),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='work_mode',
            field=models.CharField(blank=True, default='Hybrid', max_length=60),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='coredata.applicantaccount'),
        ),
        migrations.CreateModel(
            name='ApplicantLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to='coredata.applicantaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coredata.applicantaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('scope', models.CharField(db_index=True, max_length=80)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20)),
                ('source_channel', models.CharField(blank=True, default='careers_portal', max_length=80)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='India', max_length=120)),
                ('current_company', models.CharField(blank=True, max_length=160)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('expected_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('consent_to_contact', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='coredata.applicantaccount')),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_record', to='coredata.recruitmentcandidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='coredata.recruitmentjob')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('applicant', 'job')},
            },
        ),
        migrations.CreateModel(
            name='CandidateTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('applied', 'Applied'), ('stage_changed', 'Stage Changed'), ('contacted', 'Contacted'), ('note', 'Note')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='coredata.recruitmentcandidate')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='coredata.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
