# Generated by Django 5.2.8 on 2026-03-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_documentcategory_employeedocument_onboardingrecord_and_more'),
        ('employees', '0003_employee_personal_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_candidates', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='candidatetimelineevent',
            name='event_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('stage_changed', 'Stage Changed'), ('contacted', 'Contacted'), ('interview', 'Interview'), ('note', 'Note')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ProductivityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('tone', models.CharField(choices=[('amber', 'Amber'), ('coral', 'Coral'), ('ocean', 'Ocean'), ('mint', 'Mint'), ('violet', 'Violet')], default='amber', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('table_data', models.JSONField(blank=True, default=dict)),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('linked_url', models.CharField(blank=True, max_length=255)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(blank=True, max_length=120)),
                ('interview_type', models.CharField(choices=[('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('behavioral', 'Behavioral'), ('hr', 'HR'), ('final', 'Final')], db_index=True, default='screening', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mode', models.CharField(blank=True, default='virtual', max_length=40)),
                ('location_or_link', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('taken_by_role', models.CharField(blank=True, max_length=30)),
                ('panel_members', models.JSONField(blank=True, default=list)),
                ('discussion_topics', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('strong_hire', 'Strong Hire'), ('hire', 'Hire'), ('hold', 'Hold'), ('reject', 'Reject')], db_index=True, default='hold', max_length=20)),
                ('feedback_summary', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('salary_discussed', models.BooleanField(default=False)),
                ('salary_expectation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_offered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_ctc_recommended', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='coredata.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='coredata.recruitmentcandidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews', to='employees.employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='coredata.recruitmentjob')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_taken', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('reminder', 'Reminder'), ('meeting', 'Meeting'), ('interview', 'Interview'), ('payroll', 'Payroll')], db_index=True, default='event', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('remind_before_minutes', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('banner_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', '-priority'],
            },
        ),
    ]
