# Generated by Django 5.2.8 on 2026-06-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_recruitmentcandidate_employee_and_more'),
        ('employees', '0003_employee_personal_info'),
        ('payroll', '0002_payrollcomplianceprofile_employeepayroll_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Client', 'Client'), ('Software', 'Software'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim_date', models.DateField(db_index=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='employees.employee')),
                ('processed_in_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='payroll.employeepayroll')),
            ],
            options={
                'ordering': ['-claim_date', '-created_at'],
            },
        ),
    ]
