# Generated by Django 5.2.8 on 2026-06-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0007_documentesign_documentsignature'),
        ('employees', '0003_employee_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_method', models.CharField(default='web', max_length=20)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave'), ('Half Day', 'Half Day'), ('Late', 'Late')], db_index=True, default='Present', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_break', models.BooleanField(default=False)),
                ('breaks', models.JSONField(blank=True, default=list)),
                ('work_mode', models.CharField(default='Office', max_length=20)),
                ('shift', models.CharField(default='General', max_length=40)),
                ('punctuality', models.CharField(default='On time', max_length=40)),
                ('discrepancy', models.BooleanField(default=False)),
                ('discrepancy_reasons', models.JSONField(blank=True, default=list)),
                ('is_regularized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-work_date', 'employee__first_name'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
