# Generated by Django 5.2.8 on 2026-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
