# Generated by Django 5.2.8 on 2026-03-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0003_applicantaccount_and_more'),
        ('employees', '0003_employee_personal_info'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(default='India', max_length=80)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('employee_pf_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('employer_pf_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('pf_monthly_cap', models.DecimalField(decimal_places=2, default=1800, max_digits=12)),
                ('employee_esi_rate', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('employer_esi_rate', models.DecimalField(decimal_places=2, default=3.25, max_digits=5)),
                ('esi_wage_limit', models.DecimalField(decimal_places=2, default=21000, max_digits=12)),
                ('professional_tax_amount', models.DecimalField(decimal_places=2, default=200, max_digits=12)),
                ('professional_tax_threshold', models.DecimalField(decimal_places=2, default=15000, max_digits=12)),
                ('leave_salary_divisor', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('gratuity_days_factor', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('gratuity_service_years', models.PositiveIntegerField(default=5)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('notice_recovery_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='approved_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='arrears_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='compliance_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='cycle_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='deductions_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='earnings_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employee_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employee_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employer_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='extra_deductions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='extra_earnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='labour_welfare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='leave_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='loss_of_pay_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('published', 'Published'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='taxable_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('unpaid_salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('leave_encashment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('severance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statutory_deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_adjustments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_final_settlements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlements', to='employees.employee')),
                ('offboarding_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='coredata.offboardingcase')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='payroll.employeepayroll')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_final_settlements', to=settings.AUTH_USER_MODEL)),
                ('compliance_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='payroll.payrollcomplianceprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
