# Generated by Django 5.2.8 on 2026-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
