# Generated by Django 5.2.8 on 2026-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_about_employee_assets_employee_bank_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
